
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
      exclude: /META-INF/resources/templates/**


mybatis:
  type-aliases-package: com.lc.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9090
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
